version: '3.7'

services:
  # Causemos
  causemos:
    image: docker.uncharted.software/worldmodeler/wm-server:prod
    deploy:
      placement:
        constraints: [node.role != manager]
      update_config:
        parallelism: 1
        delay: 60s
        failure_action: rollback
      restart_policy:
        condition: any
      replicas: 1
      resources:
        limits:
          memory: 1048M
          cpus: '2'
    secrets:
      - source: CAUSEMOS_ENV_FILE
        target: /server/.env
    logging:
      driver: "json-file"
      options:
        max-size: "400k"
        max-file: "2"
    networks:
      - common-net
    ports:
      - "3003:3000"
    extra_hosts:
      - "host.docker.internal:host-gateway"

secrets:
  CAUSEMOS_ENV_FILE:
    file: ./envs/causemos.env

networks:
  common-net:
    name: common-net
    driver: bridge
